//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IntegradorDeGP.BLL
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwSopFacturasCabezaTH
    {
        public short soptype { get; set; }
        public string sopnumbe { get; set; }
        public Nullable<short> voidstts { get; set; }
        public string custnmbr { get; set; }
        public System.DateTime docdate { get; set; }
        public string docid { get; set; }
        public string curncyid { get; set; }
        public short pstgstus { get; set; }
        public string cstponbr { get; set; }
    }
}
